ALTER TABLE GEO_ARTICLE
MODIFY PLU_CODE VARCHAR2(10 BYTE);

ALTER TABLE GEO_PLU
MODIFY PLU_CODE VARCHAR2(10 BYTE);

ALTER TABLE GEO_ARTICLE_DUPLIQ
MODIFY PLU_CODE VARCHAR2(10 BYTE)
ADD (
	COL_PDNET_TMP NUMBER(8,3) DEFAULT NULL,
	REF_CDC  VARCHAR2(6 BYTE),
	REF_EMBALLAGE VARCHAR2(6 BYTE),
	REF_MAT_PREM  VARCHAR2(6 BYTE),
	REF_NORMALISATION VARCHAR2(6 BYTE)
);

ALTER TABLE GEO_ARTICLE_DELETE
MODIFY PLU_CODE VARCHAR2(10 BYTE)
ADD (
	COL_PDNET_TMP NUMBER(8,3) DEFAULT NULL,
	REF_CDC  VARCHAR2(6 BYTE),
	REF_EMBALLAGE VARCHAR2(6 BYTE),
	REF_MAT_PREM  VARCHAR2(6 BYTE),
	REF_NORMALISATION VARCHAR2(6 BYTE)
);
/

