ALTER TABLE GEO_ORDFRA ADD ACH_QTE NUMBER(10,3);
ALTER TABLE GEO_ORDFRA ADD ACH_PU NUMBER(12,2);
ALTER TABLE GEO_ORDFRA ADD ACH_DEV_PU NUMBER(12,2);
ALTER TABLE GEO_ORDFRA ADD MONTANT_TOT NUMBER(12,2);

UPDATE GEO_ADMIN.GEO_ORDFRA SET
ACH_QTE = 1,
ACH_DEV_PU = MONTANT,
MONTANT_TOT = MONTANT * DEV_TX,
ACH_PU = MONTANT * DEV_TX;
/

