-------------------
-- geo_modif_corps
-------------------

CREATE TABLE GEO_ADMIN.GEO_MODIF_CORPS (
	K_MODIF_CORPS NUMBER NOT NULL,
	MODIF NUMBER NOT NULL,
	CHEMIN VARCHAR2(100) NOT NULL,
	TRADUCTION_KEY VARCHAR2(100),
	VALEUR_ACTUELLE VARCHAR2(500) NOT NULL,
	VALEUR_DEMANDEE VARCHAR2(500) NOT NULL,
	AFFICHAGE_ACTUEL VARCHAR2(100),
	AFFICHAGE_DEMANDE VARCHAR2(100),
	VALIDATEUR VARCHAR2(35) NOT NULL,
	MOD_DATE DATE
);

ALTER TABLE GEO_ADMIN.GEO_MODIF_CORPS
ADD CONSTRAINT GEO_MODIF_CORPS_PK PRIMARY KEY (K_MODIF_CORPS)
ENABLE;

ALTER TABLE GEO_ADMIN.GEO_MODIF_CORPS ADD CONSTRAINT FK_MODIF_CORPS_USER FOREIGN KEY (VALIDATEUR) REFERENCES GEO_ADMIN.GEO_USER(NOM_UTILISATEUR);

COMMENT ON COLUMN GEO_ADMIN.GEO_MODIF_CORPS.K_MODIF_CORPS IS 'Primary key';
COMMENT ON COLUMN GEO_ADMIN.GEO_MODIF_CORPS.MODIF IS 'GEO_MODIF Foreign key';
COMMENT ON COLUMN GEO_ADMIN.GEO_MODIF_CORPS.CHEMIN IS 'Chemin du champ (frontend)';
COMMENT ON COLUMN GEO_ADMIN.GEO_MODIF_CORPS.TRADUCTION_KEY IS 'Clé de traduction (frontend)';
COMMENT ON COLUMN GEO_ADMIN.GEO_MODIF_CORPS.VALEUR_ACTUELLE IS 'Valeur actuelle du champ (clé ou valeur)';
COMMENT ON COLUMN GEO_ADMIN.GEO_MODIF_CORPS.VALEUR_DEMANDEE IS 'Valeur demandée (clé ou valeur)';
COMMENT ON COLUMN GEO_ADMIN.GEO_MODIF_CORPS.AFFICHAGE_ACTUEL IS 'Affichage actuel du champ';
COMMENT ON COLUMN GEO_ADMIN.GEO_MODIF_CORPS.AFFICHAGE_DEMANDE IS 'Affichage demandé';
COMMENT ON COLUMN GEO_ADMIN.GEO_MODIF_CORPS.VALIDATEUR IS 'Utilisateur validant les modifications';
COMMENT ON COLUMN GEO_ADMIN.GEO_MODIF.MOD_DATE IS 'Date de création ou modification';

CREATE SEQUENCE GEO_ADMIN.SEQ_KEY_MODIF_CORPS INCREMENT BY 1 MINVALUE 0 NOCYCLE NOCACHE NOORDER ;
