-------------------
-- geo_modif
-------------------

CREATE TABLE GEO_ADMIN.GEO_MODIF (
	K_MODIF NUMBER NOT NULL,
	ENTITE VARCHAR2(30) NOT NULL,
	STATUT CHAR(1) NOT NULL,
	ENTITE_KEY VARCHAR2(6) NOT NULL,
	UTILISATEUR VARCHAR2(35) NOT NULL,
	MOD_DATE DATE
);

ALTER TABLE GEO_ADMIN.GEO_MODIF MODIFY STATUT CHAR(1) DEFAULT 'N';

ALTER TABLE GEO_ADMIN.GEO_MODIF
ADD CONSTRAINT GEO_MODIF_PK PRIMARY KEY (K_MODIF)
ENABLE;

CREATE INDEX GEO_MODIF_ENTITE_IDX ON GEO_ADMIN.GEO_MODIF (ENTITE,STATUT,ENTITE_KEY);

ALTER TABLE GEO_ADMIN.GEO_MODIF ADD CONSTRAINT FK_MODIF_USER FOREIGN KEY (UTILISATEUR) REFERENCES GEO_ADMIN.GEO_USER(NOM_UTILISATEUR);

COMMENT ON TABLE GEO_ADMIN.GEO_MODIF IS 'Modifications / historique pour la validation des formulaires';
COMMENT ON COLUMN GEO_ADMIN.GEO_MODIF.K_MODIF IS 'Primary key';
COMMENT ON COLUMN GEO_ADMIN.GEO_MODIF.ENTITE IS 'Nom de l''entité';
COMMENT ON COLUMN GEO_ADMIN.GEO_MODIF.STATUT IS 'Modifications traitées / vues';
COMMENT ON COLUMN GEO_ADMIN.GEO_MODIF.ENTITE_KEY IS 'ID de l''entité';
COMMENT ON COLUMN GEO_ADMIN.GEO_MODIF.UTILISATEUR IS 'Initiateur';
COMMENT ON COLUMN GEO_ADMIN.GEO_MODIF.MOD_DATE IS 'Date de création ou modification';

CREATE SEQUENCE GEO_ADMIN.SEQ_KEY_MODIF INCREMENT BY 1 MINVALUE 0 NOCYCLE NOCACHE NOORDER ;
