----------------
-- geo_mru_ordre
----------------

DELETE FROM GEO_MRU_ORDRE WHERE ORD_REF IN(
    SELECT DISTINCT gmo.ORD_REF
    FROM GEO_ORDRE go
    RIGHT JOIN GEO_MRU_ORDRE gmo ON gmo.ORD_REF = go.ORD_REF
    WHERE go.ORD_REF IS NULL
);
/

ALTER TABLE "GEO_ADMIN"."GEO_MRU_ORDRE"
    ADD CONSTRAINT "FK_MRU_ORDRE_ORDRE" FOREIGN KEY("ORD_REF")
    REFERENCES "GEO_ADMIN"."GEO_ORDRE"("ORD_REF") ON DELETE CASCADE;
/

ALTER TABLE "GEO_ADMIN"."GEO_MRU_ORDRE"
    ADD CONSTRAINT "FK_MRU_ORDRE_SOCIETE" FOREIGN KEY("SOC_CODE")
    REFERENCES "GEO_ADMIN"."GEO_SOCIETE"("SOC_CODE") ON DELETE CASCADE;
/

DELETE FROM GEO_MRU_ORDRE WHERE NOM_UTILISATEUR IN(
    SELECT DISTINCT gmo.NOM_UTILISATEUR
    FROM GEO_USER gu
    RIGHT JOIN GEO_MRU_ORDRE gmo ON gmo.NOM_UTILISATEUR = gu.NOM_UTILISATEUR
    WHERE gu.NOM_UTILISATEUR IS NULL
);
/

ALTER TABLE "GEO_ADMIN"."GEO_MRU_ORDRE" 
    ADD CONSTRAINT "FK_MRU_ORDRE_USER" FOREIGN KEY("NOM_UTILISATEUR")
    REFERENCES "GEO_ADMIN"."GEO_USER"("NOM_UTILISATEUR") ON DELETE CASCADE ;
/
	
create index IX_MRU_ORDRE_NOM_UTILISATEUR on GEO_MRU_ORDRE (NOM_UTILISATEUR);
/

create index IX_MRU_ORDRE_SOCIETE on GEO_MRU_ORDRE (SOC_CODE);
/
