----------------
-- geo_mru_ordre
----------------

ALTER TABLE "GEO_ADMIN"."GEO_MRU_ORDRE" 
    ADD CONSTRAINT "FK_MRU_ORDRE_ORDRE" FOREIGN KEY("ORD_REF")
    REFERENCES "GEO_ADMIN"."GEO_ORDRE"("ORD_REF") ON DELETE CASCADE;
/
	
ALTER TABLE "GEO_ADMIN"."GEO_MRU_ORDRE" 
    ADD CONSTRAINT "FK_MRU_ORDRE_SOCIETE" FOREIGN KEY("SOC_CODE")
    REFERENCES "GEO_ADMIN"."GEO_SOCIETE"("SOC_CODE") ON DELETE CASCADE;
/

ALTER TABLE "GEO_ADMIN"."GEO_MRU_ORDRE" 
    ADD CONSTRAINT "FK_MRU_ORDRE_USER" FOREIGN KEY("NOM_UTILISATEUR")
    REFERENCES "GEO_ADMIN"."GEO_USER"("NOM_UTILISATEUR") ON DELETE CASCADE ;
/
	
create index IX_MRU_ORDRE_NOM_UTILISATEUR on GEO_MRU_ORDRE (NOM_UTILISATEUR);
/

create index IX_MRU_ORDRE_SOCIETE on GEO_MRU_ORDRE (SOC_CODE);
/
