DROP TABLE "GEO_ADMIN"."GEO_GRID_CONFIG";
CREATE TABLE "GEO_ADMIN"."GEO_GRID_CONFIG"
   (
    "UTILISATEUR" VARCHAR2(35) NOT NULL ENABLE,
	"GRID" VARCHAR2(100) NOT NULL ENABLE,
	"SOC_CODE" VARCHAR2(3) NOT NULL ENABLE,
	"CONFIG" BLOB NOT NULL ENABLE,
	"MOD_USER" VARCHAR2(35),
	"MOD_DATE" DATE,
	 CONSTRAINT "FK_GEO_USER" FOREIGN KEY ("UTILISATEUR")
	  REFERENCES "GEO_ADMIN"."GEO_USER" ("NOM_UTILISATEUR") ENABLE,
	 CONSTRAINT "FK_GEO_SOCIETE" FOREIGN KEY ("SOC_CODE")
	  REFERENCES "GEO_ADMIN"."GEO_SOCIETE" ("SOC_CODE") ENABLE
   );

ALTER TABLE GEO_ADMIN.GEO_GRID_CONFIG
ADD CONSTRAINT GEO_GRID_CONFIG_PK PRIMARY KEY (UTILISATEUR,GRID,SOC_CODE)
ENABLE;
/

