# Build the image from the current Dockerfile

matrix:
    PLATFORM:
        - linux/amd64
    JAVA_VERSION:
        - 11

when:
    event: push
    branch: [master, next, "ci"]

platform: ${PLATFORM}

pipeline:
    - name: compile
      image: eclipse-temurin:${JAVA_VERSION}
      commands:
          - ./mvnw compile
    # share-images: TODO registry
