CREATE OR REPLACE TRIGGER GEO_ENVOIS_AFTER_UPDATE_INSERT
AFTER UPDATE OR INSERT ON GEO_ADMIN.GEO_ENVOIS FOR EACH ROW
WHEN (NEW.TRAIT_EXP = 'N')
BEGIN
    INSERT INTO GEO_ADMIN.GEO_DEPOT_ENVOI (ORD_REF)
    VALUES (:NEW.ORD_REF);
END;
/
