ALTER TABLE  GEO_GEST_REGROUP ADD COL_PDNET NUMBER (8,3);
ALTER TABLE  GEO_GEST_REGROUP ADD COL_PDNET_MOY NUMBER (8,3);
ALTER TABLE  GEO_ENVOIS ADD DAT_TRAIT_EXP DATE;
ALTER TABLE GEO_TYPORD 	ADD  IND_CONS_PAL VARCHAR2(1) DEFAULT 'N';
commit;
COMMENT ON COLUMN GEO_TYPORD.IND_CONS_PAL IS 'indicateur de génération consigne palox';
commit;
update GEO_TYPORD SET IND_CONS_PAL ='O' where TYP_ORD in ('COM','ORD');
commit;
