ALTER TABLE AVI_ART_GESTION
MODIFY ART_ALPHA VARCHAR2(70 BYTE);
COMMIT;

ALTER TABLE GEO_ARTDEM
MODIFY ART_ALPHA VARCHAR2(70 BYTE);
COMMIT;

ALTER TABLE GEO_ARTICLE
MODIFY ART_ALPHA VARCHAR2(70 BYTE);
COMMIT;

ALTER TABLE GEO_ARTICLE_DELETE
MODIFY ART_ALPHA VARCHAR2(70 BYTE);
COMMIT;

ALTER TABLE GEO_ARTICLE_DUPLIQ
MODIFY ART_ALPHA VARCHAR2(70 BYTE);
COMMIT;
