CREATE OR REPLACE TRIGGER GEO_ENVOIS_AFTER_UPDATE_INSERT
AFTER UPDATE OR INSERT ON GEO_ADMIN.GEO_ENVOIS FOR EACH ROW
WHEN (NEW.TRAIT_EXP = 'N')
DECLARE
	count_res NUMBER;
BEGIN
	SELECT count(*) INTO count_res FROM GEO_ADMIN.GEO_DEPOT_ENVOI WHERE ORD_REF = :NEW.ORD_REF;
	IF count_res = 0 then
    	INSERT INTO GEO_ADMIN.GEO_DEPOT_ENVOI (ORD_REF) VALUES (:NEW.ORD_REF);
    END IF;
END;
/
