-------------------
-- geo_grid_config
-------------------

CREATE TABLE GEO_ADMIN.GEO_GRID_CONFIG (
	UTILISATEUR VARCHAR2(35) NOT NULL,
	GRID VARCHAR2(100) NOT NULL,
	CONFIG BLOB NOT NULL
);

ALTER TABLE GEO_ADMIN.GEO_GRID_CONFIG
ADD CONSTRAINT GEO_GRID_CONFIG_PK PRIMARY KEY (UTILISATEUR,GRID)
ENABLE;

ALTER TABLE GEO_ADMIN.GEO_GRID_CONFIG ADD CONSTRAINT FK_GEO_USER FOREIGN KEY (UTILISATEUR) REFERENCES GEO_ADMIN.GEO_USER(NOM_UTILISATEUR);
