ALTER TABLE GEO_ADMIN.GEO_GRID_CONFIG ADD MOD_USER VARCHAR2(35);
ALTER TABLE GEO_ADMIN.GEO_GRID_CONFIG ADD MOD_DATE DATE;
ALTER TABLE GEO_ADMIN.GEO_GRID_CONFIG ADD SOC_CODE VARCHAR2(3) NULL;
ALTER TABLE GEO_ADMIN.GEO_GRID_CONFIG ADD CONSTRAINT FK_GEO_SOCIETE FOREIGN KEY (SOC_CODE) REFERENCES GEO_ADMIN.GEO_SOCIETE(SOC_CODE);
/

