ALTER TABLE GEO_HISTO_ARTICLE MODIFY (COMM_HISTO varchar2(512));
ALTER TABLE GEO_HISTO_CLIENT MODIFY (COMM_HISTO varchar2(512));
ALTER TABLE GEO_HISTO_FOURNI MODIFY (COMM_HISTO varchar2(512));
ALTER TABLE GEO_HISTO_TRANSP MODIFY (COMM_HISTO varchar2(512));
/

