-- TABLE AVI_ART_MAT_PREM
CREATE TABLE AVI_ART_MAT_PREM
(
    REF_MAT_PREM VARCHAR2(6 BYTE),
    ESP_CODE     VARCHAR2(6 BYTE) NOT NULL,
    VAR_CODE     VARCHAR2(6 BYTE) NOT NULL,
    CAF_CODE     VARCHAR2(6 BYTE),
    CUN_CODE     VARCHAR2(6 BYTE) NOT NULL,
    ORI_CODE     VARCHAR2(6 BYTE) NOT NULL,
    MODE_CULTURE NUMBER(2)        DEFAULT 0,
    TYP_CODE     VARCHAR2(6 BYTE),
    TYP_REF      VARCHAR2(6 BYTE),
    TVT_CODE     VARCHAR2(1 BYTE),
    PLU_CODE     VARCHAR2(4 BYTE),
    CRE_USER     VARCHAR2(35 BYTE),
    CRE_DATE     DATE,
    MOD_USER     VARCHAR2(35 BYTE),
    MOD_DATE     DATE,
    VALIDE       VARCHAR2(1 BYTE) DEFAULT 'O'
)
    TABLESPACE GEO_DATA
    PCTUSED 0
    PCTFREE 10
    INITRANS 1
    MAXTRANS 255
    STORAGE
(
    INITIAL 3M
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    PCTINCREASE 0
    BUFFER_POOL DEFAULT
)
    LOGGING
    NOCACHE
    NOPARALLEL;

ALTER TABLE AVI_ART_MAT_PREM
    ADD (
        CONSTRAINT FK_MAT_PREM_ESPECE FOREIGN KEY (ESP_CODE)
            REFERENCES GEO_ESPECE (ESP_CODE));

ALTER TABLE AVI_ART_MAT_PREM
    ADD (
        CONSTRAINT FK_MAT_PREM_ORIGINE FOREIGN KEY (ESP_CODE, ORI_CODE)
            REFERENCES GEO_ORIGINE (ESP_CODE, ORI_CODE));

ALTER TABLE AVI_ART_MAT_PREM
    ADD (
        CONSTRAINT FK_MAT_PREM_VARIET FOREIGN KEY (VAR_CODE)
            REFERENCES GEO_VARIET (VAR_CODE));

ALTER TABLE AVI_ART_MAT_PREM
    ADD (
        CONSTRAINT FK_MAT_PREM_MODE_CULTURE FOREIGN KEY (MODE_CULTURE)
            REFERENCES GEO_MODE_CULTURE (REF) DISABLE);

ALTER TABLE AVI_ART_MAT_PREM
    ADD (
        CONSTRAINT FK_MAT_PREM_TYP FOREIGN KEY (TYP_REF)
            REFERENCES GEO_TYP (TYP_REF));

ALTER TABLE AVI_ART_MAT_PREM
    ADD (
        CONSTRAINT FK_MAT_PREM_TYPVTE FOREIGN KEY (TVT_CODE)
            REFERENCES GEO_TYPVTE (TVT_CODE));

COMMENT ON COLUMN AVI_ART_MAT_PREM.ESP_CODE IS 'FK espèce (redondance speed)';
COMMENT ON COLUMN AVI_ART_MAT_PREM.VAR_CODE IS 'FK variété';
COMMENT ON COLUMN AVI_ART_MAT_PREM.ORI_CODE IS 'FK origine';
COMMENT ON COLUMN AVI_ART_MAT_PREM.CUN_CODE IS 'FK calibre unifié';
COMMENT ON COLUMN AVI_ART_MAT_PREM.CAF_CODE IS 'FK calibre fournisseur';
COMMENT ON COLUMN AVI_ART_MAT_PREM.TYP_REF IS 'FK TYP';
COMMENT ON COLUMN AVI_ART_MAT_PREM.MODE_CULTURE IS '0 = conventionel ; 1 = conversion ; 2 = bio ; 3 = zéro résidu';
COMMENT ON COLUMN AVI_ART_MAT_PREM.TVT_CODE IS 'FK type de vente';

CREATE OR REPLACE TRIGGER AVI_ART_MAT_PREM_BEF_INS
    BEFORE INSERT
    ON AVI_ART_MAT_PREM
    FOR EACH ROW
declare
    x_user varchar2(35);
begin
    if (:new.cre_user is null) then
        select sys_context('USERENV', 'OS_USER') into x_user from dual;
        :new.cre_user := x_user;
    end if;
    if (:new.cre_date is null) then
        :new.cre_date := sysdate;
    end if;
    if (:new.valide is null) then
        :new.valide := 'O';
    end if;
end;
/
SHOW ERRORS;


CREATE OR REPLACE TRIGGER AVI_ART_MAT_PREM_BEF_UPD
    BEFORE UPDATE
    ON AVI_ART_MAT_PREM
    FOR EACH ROW
declare
    x_user varchar2(35);
begin
    if (:new.mod_user is null) then
        select sys_context('USERENV', 'OS_USER') into x_user from dual;
        :new.mod_user := x_user;
    end if;
    if (:new.mod_date is null) then
        :new.mod_date := sysdate;
    end if;
end;
/
SHOW ERRORS;

ALTER TABLE AVI_ART_MAT_PREM
    ADD (
        CONSTRAINT PK_AVI_ART_MAT_PREM PRIMARY KEY (REF_MAT_PREM)
            USING INDEX
                TABLESPACE GEO_INDX
                PCTFREE 10
                INITRANS 2
                MAXTRANS 255
                STORAGE (
                INITIAL 1032 K
                MINEXTENTS 1
                MAXEXTENTS 2147483645
                PCTINCREASE 0
                ));

CREATE UNIQUE INDEX UNIQUE_ART_MAT_PREM ON AVI_ART_MAT_PREM
    (ESP_CODE, VAR_CODE, CAF_CODE, CUN_CODE, ORI_CODE, MODE_CULTURE, TYP_REF, TVT_CODE, PLU_CODE)
    LOGGING
    TABLESPACE GEO_INDX
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (
    INITIAL 1032 K
    MINEXTENTS 1
    MAXEXTENTS 2147483645
    PCTINCREASE 0
    BUFFER_POOL DEFAULT
    )
    NOPARALLEL;

CREATE SEQUENCE GEO_ADMIN.SEQ_AVI_ART_MAT_PREM START WITH 0 NOMAXVALUE MINVALUE 0 NOCYCLE NOCACHE NOORDER;
CREATE OR REPLACE FUNCTION F_SEQ_AVI_ART_MAT_PREM
    RETURN VARCHAR2 IS
    result VARCHAR2(6);
BEGIN
    SELECT TO_CHAR(seq_AVI_ART_MAT_PREM.NEXTVAL, 'FM0XXXXX') INTO result FROM dual;
    RETURN result;
END;
/
